//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksGridView
{
    using System;
    using System.Collections.Generic;
    
    public partial class books_new
    {
        public int N { get; set; }
        public Nullable<double> Code { get; set; }
        public bool New { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<double> Pages { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Pressrun { get; set; }
        public Nullable<int> izd_id { get; set; }
        public Nullable<int> format_id { get; set; }
        public Nullable<int> themes_id { get; set; }
        public Nullable<int> kategory_id { get; set; }
    
        public virtual Spr_format Spr_format { get; set; }
        public virtual Spr_izd Spr_izd { get; set; }
        public virtual Spr_kategory Spr_kategory { get; set; }
        public virtual Spr_themes Spr_themes { get; set; }
    }
}
