//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksGridView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spr_themes
    {
        public Spr_themes()
        {
            this.books_new = new HashSet<books_new>();
        }
    
        public string Themes { get; set; }
        public int id { get; set; }
    
        public virtual ICollection<books_new> books_new { get; set; }
    }
}
